version: 2.1
commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy frontend environment
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}
      - run:
          name: Destroy backend environment
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: build-front
          command: |
            cd frontend  
            npm install
            npm run build
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: build-back
          command: |
            cd backend
            npm install
            npm run build
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: test-front
          command: |
            cd frontend
            npm install
            npm run test
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: test-back
          command: |
            cd backend
            npm install
            npm run test
  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: scan-front
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical
  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: scan-back
          command: |
            cd backend
            npm install
            npm audit fix --legacy-peer-deps
            npx npm-force-resolutions
            npm audit --audit-level=critical
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install -y tar gzip
      - run: aws cloudformation deploy \
        --template-file .circleci/files/backend.yml \
        --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
        --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
        --tags project=udapeople
      - run: aws cloudformation deploy \
        --template-file .circleci/files/frontend.yml \
        --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
        --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
        --tags project=udapeople
      - destroy_environment

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [test-frontend]
      - scan-backend:
          requires: [test-backend]
      - deploy-infrastructure:
          requires: [scan-backend,scan-frontend]
